services:
  opencode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-doctor-opencode
    ports:
      - "4097:4096"
    volumes:
      - ./data/notes:/home/aiuser/Codes/ai-doctor-opencode/notes
      - ./notes:/home/aiuser/Codes/ai-doctor/opencode/notes
    working_dir: /home/aiuser/Codes
    restart: on-failure:5
    command: /home/aiuser/.opencode/bin/opencode web --port 4096 --hostname 0.0.0.0
